[package]
name = "mkfatfs"
version = "0.1.0"
authors = ["Opal Symes <code@opal.codes>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.4.2"
fatfs = "0.3"
regex = "1"
structopt = "0.3"
